# .streamlit/secrets.toml

[users]
testuser = "9f735e0df9a1ddc702bf0a1a7b83033f9f7153a00c29de82cedadc9957289b05"

# To add a new user, add a new line like this:
# username = "sha256_hashed_password"
# You can generate the hash by running this command in your terminal:
# echo -n "your_password" | shasum -a 256
